import cx_Freeze

executables = [cx_Freeze.Executable("Main.py")]
cx_Freeze.setup(
    name="Joyeux Nowel !",
    options={"build_exe": {"packages": ["pygame"],
                           "include_files": ["Icon.png", "BBSChristmasOST.wav", "JoyeuxNoel.png", "Menu.png",
                                             "Game1/Hogyoku.png", "Game1/FondGame1.png", "Game1/Gin.png",
                                             "Game1/InstructionsNormal.png", "Game1/Loose.png",
                                             "Game1/OSTBleachTreachery.wav", "Game1/Win.png", "Game1/WinHard.png",
                                             "Game1/InstructionsHard.png", "Game1/HardNormal.png",
                                             "OSTBleachHollowed.wav", "Game2/Choice.png", "Game2/ChoiceEnding.png",
                                             "Game2/ChoiceOpening.png", "Game2/ChoiceOST.png", "Game2/Faux.png",
                                             "Game2/Vrai.png", "Game2/InstructionsGame2.png", "Game2/Score.png",
                                             "Game2/ScoreLoose.png", "Game2/Endings/Ed01.wav",
                                             "Game2/Openings/Op02.wav", "Game2/Openings/Op06.wav",
                                             "Game2/Openings/Op08.wav", "Game2/Openings/Op09.wav",
                                             "Game2/Openings/Op11.wav", "Game2/Openings/Op13.wav",
                                             "Game2/Openings/Op15.wav", "Game2/Openings/Op16.wav",
                                             "Game2/Endings/Ed03.wav", "Game2/Endings/Ed05.wav",
                                             "Game2/Endings/Ed09.wav", "Game2/Endings/Ed10.wav",
                                             "Game2/Endings/Ed17.wav", "Game2/Endings/Ed20.wav",
                                             "Game2/Endings/Ed22.wav", "Game2/Endings/Ed25.wav",
                                             "Game2/Endings/Ed26.wav", "Game2/Endings/Ed27.wav",
                                             "Game2/Endings/Ed28.wav", "Game2/Endings/Ed30.wav",
                                             "Game2/OST/EncirclementBattle.wav", "Game2/OST/FadeToBlack.wav",
                                             "Game2/OST/Senna.wav", "Game2/OST/Invasion.wav",
                                             "Game2/OST/TornAppart.wav", "FinalGame/Aizen1.png", "FinalGame/Aizen2.png",
                                             "FinalGame/Aizen3.png", "FinalGame/Aizen4.png", "FinalGame/Aizen5.png",
                                             "FinalGame/AizenHado90.wav", "FinalGame/Code.png",
                                             "FinalGame/Combattre.png", "FinalGame/FondFinalGame.png",
                                             "FinalGame/Gin.png", "FinalGame/GinDeath.mpg", "FinalGame/Komamura.png",
                                             "FinalGame/Power1.png", "FinalGame/Power2.png", "FinalGame/Power3.png",
                                             "FinalGame/Power4.png", "FinalGame/Power5.png", "FinalGame/Lag.png",
                                             "FinalGame/GG.png", "SummonSimulator/A.png", "SummonSimulator/D.png",
                                             "SummonSimulator/E.png", "SummonSimulator/Gin3.png",
                                             "SummonSimulator/Gin4.png", "SummonSimulator/GinCat.png",
                                             "SummonSimulator/GinOrange.png", "SummonSimulator/GinViolet.png",
                                             "SummonSimulator/GinWD.png", "SummonSimulator/N.png",
                                             "SummonSimulator/Proba.png", "SummonSimulator/Star4.mpg",
                                             "SummonSimulator/Star4.wav", "SummonSimulator/Star5.mpg",
                                             "SummonSimulator/Star5.wav", "SummonSimulator/Summon.png",
                                             "SummonSimulator/SummonFond.png", "SummonSimulator/Triste.wav",
                                             "SummonSimulator/Yeah.wav", "SummonSimulator/WBToBBS.wav"]}},
    author="PyroWilDx",
    version="1.0.0",
    executables=executables
)
